import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Cursor from "@/components/cursor";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased neue`}
      >
        <Cursor />
        {children}
      </body>
    </html>
  );
}
